name: Deploy to Render on main branch push!

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Debug: show deploy URL"
        run: echo "Deploy URL is ${{ secrets.RENDER_DEPLOY_URL }}"

      - name: Trigger Render deployment (verbose curl)
        run: curl -v -X GET "${{ secrets.RENDER_DEPLOY_URL }}"
