name: Deploy to Render on main branch push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Send GET request to Render
        run: curl -X GET "${{ secrets.RENDER_DEPLOY_URL }}"
